# based on an example from https://github.com/r-lib/actions/tree/master/examples

name: Update data

on:
  schedule:
    - cron:  '45 16 * * *' # everyday at 04:05 UTC

#push:
#    paths:
#    - 'Readme.md'
      
jobs:
  update_data:
    runs-on: macos

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    # Setup R and its depedencies
    - uses: r-lib/actions/setup-r@master
    - name: Install R dependencies
      run: |
         install.packages(c("remotes", "here", "tidyverse", "magrittr", "lubridate")) 
         remotes::install_deps(dependencies = TRUE)
      shell: Rscript {0}
      
    # Prepare data
    - name: Prepare data with R
      run: Rscript Mobility_GroundTraffic.R

    # Commit to repo with updated file
    - uses: stefanzweifel/git-auto-commit-action@v4.1.1
      with:
        commit_message: Update csv
        branch: ${{ github.head_ref }}
